# Generated by Django 5.2.5 on 2025-09-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larpmanager', '0076_warehouseitem_rename_inventoryarea_warehousearea_and_more'),
        ('larpmanager', '0083_remove_abilitytemplatepx_components_and_more'),
    ]

    operations = [
    ]
