services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: larpmanager
      POSTGRES_USER: larpuser
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest

  main:
    build: .
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: changeme
      ADMIN_NAME: yourname
      ADMIN_EMAIL: youremail
      DB_NAME: larpmanager
      DB_USER: larpuser
      DB_PASS: changeme
      DB_HOST: db
      REDIS_URL: redis://redis:6379
      GOOGLE_CLIENTID: changeme
      GOOGLE_SECRET: changeme
      RECAPTCHA_PUBLIC: changeme
      RECAPTCHA_PRIVATE: changeme
      env: prod
      TZ: Europe/Rome
      DJANGO_SETTINGS_MODULE: main.settings

volumes:
  pgdata:
