name: Auto-approve my PRs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-approve:
    if: github.actor == 'loskana'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}